const CONFIG = {
  // The title shown in the browser tab
  siteTitle: "Gift for my love",

  backgroundImage: "",

  // Side A art. Shown by default.
  vinylArt: "assets/images/album.jpg",
  // Side B art, shown after clicking "flip". Add a second image and update this path.
  vinylArtSideB: "assets/images/album-b.jpg",

  // The message revealed when the hidden letter (bottom-right of the gallery) is opened.
  // Use \n\n for paragraph breaks.
  hiddenLetterText:
    "If you found this, you weren't just looking at the photos \u2014 you were looking closely.\n\nThat's kind of the whole point of us.",

  // Simple passphrase gating the journal. NOTE: since this is a static site with
  // no server, this is a light "keep out casual visitors" gate, not real security \u2014
  // anyone who inspects the page source could find it. Fine for a private gift link,
  // just don't rely on it for anything truly sensitive.
  journalPassword: "changeme",
};

const playlist = [
  { title: "Waking Up Slow",      youtubeId: "cTSdJEGswtg" },
  { title: "Flightless Bird, American Mouth",      youtubeId: "RGVmhrfQqzg" },
  { title: "Stay Love",    youtubeId: "hLWLS-Csppw" },
  { title: "Ordinary",     youtubeId: "NaZznqme2hg" },
  { title: "Sweet Love",     youtubeId: "Q-p2mVc8qsQ" },
  { title: "Iris",      youtubeId: "hpy8F9uzqv0" },
  { title: "Bad Dreams",    youtubeId: "iMIZf1YY0zs" },
  { title: "Runnin' Home to You",    youtubeId: "f4a1vf7l-jI" },
  { title: "San Luis",     youtubeId: "7BJ7MDOmLPE" },
  { title: "Bloom",      youtubeId: "8inJtTG_DuU" },
  { title: "Amsterdam",   youtubeId: "lz2qpnRB5_E" },
  { title: "Tenerife Sea", youtubeId: "2tHes1FQfwU" },
  { title: "If We Were Vampires",   youtubeId: "246pND4SGXk" },
];

const photos = [
  { src: "assets/images/photo1.jpg",  caption: "" },
  { src: "assets/images/photo2.jpg",  caption: "" },
  { src: "assets/images/photo3.jpg",  caption: "" },
  { src: "assets/images/photo4.jpg",  caption: "" },
  { src: "assets/images/photo5.jpg",  caption: "" },
  { src: "assets/images/photo6.jpg",  caption: "" },
  { src: "assets/images/photo7.jpg",  caption: "" },
  { src: "assets/images/photo8.jpg",  caption: "" },
  { src: "assets/images/photo9.jpg",  caption: "" },
  { src: "assets/images/photo10.jpg", caption: "" },
  { src: "assets/images/photo11.jpg", caption: "" },
  { src: "assets/images/photo12.jpg", caption: "" },
  { src: "assets/images/photo13.jpg", caption: "" },
];


// Journal entries. New entries are generated by the "+" button on the journal
// screen as a ready-to-paste snippet \u2014 copy it in here (inside this array) and
// redeploy so it becomes a permanent, shared entry rather than a browser-only preview.
const journalEntries = [
  // { date: "July 8, 2026", text: "Today I..." },
];


(function () {
  "use strict";

  function applyConfig() {
    document.title = CONFIG.siteTitle;

    if (CONFIG.backgroundImage) {
      const backdrop = document.getElementById("home-backdrop");
      backdrop.style.backgroundImage =
        `linear-gradient(180deg, rgba(243,236,221,0.55), rgba(228,212,180,0.72)), url("${CONFIG.backgroundImage}")`;
      backdrop.style.backgroundSize = "cover";
      backdrop.style.backgroundPosition = "center";
    }

    const miniArt = document.getElementById("mini-vinyl-art");
    const playerArt = document.getElementById("player-vinyl-art");
    if (miniArt) miniArt.src = CONFIG.vinylArt;
    if (playerArt) playerArt.src = CONFIG.vinylArt;
  }

  const screens = {
    home: document.getElementById("home-screen"),
    player: document.getElementById("player-screen"),
    gallery: document.getElementById("gallery-screen"),
    journal: document.getElementById("journal-screen"),
  };

  function showScreen(name, keepMusic) {
    Object.entries(screens).forEach(([key, el]) => {
      if (!el) return;
      el.classList.toggle("is-active", key === name);
    });

    if (name !== "player" && !keepMusic) {
      pausePlayback();
    }
  }

  function initNavigation() {
    const openPlayer = document.getElementById("open-player");
    const openGallery = document.getElementById("open-gallery");
    const openJournal = document.getElementById("open-journal");
    const backButtons = document.querySelectorAll("[data-back]");
    const backKeepMusicButtons = document.querySelectorAll("[data-back-keep-music]");

    openPlayer.addEventListener("click", () => {
      showScreen("player");
      playSongAt(0);
    });

    openGallery.addEventListener("click", () => {
      triggerCameraFlash();
      showScreen("gallery");
    });

    openJournal.addEventListener("click", () => {
      showScreen("journal");
      refreshJournalLockState();
    });

    backButtons.forEach((btn) =>
      btn.addEventListener("click", () => showScreen("home"))
    );

    backKeepMusicButtons.forEach((btn) =>
      btn.addEventListener("click", () => showScreen("gallery", true))
    );
  }

  function triggerCameraFlash() {
    const flash = document.querySelector(".mini-camera__flash-burst");
    if (!flash) return;
    flash.classList.add("is-flashing");
    flash.addEventListener("animationend", function handler() {
      flash.classList.remove("is-flashing");
      flash.removeEventListener("animationend", handler);
    });
  }

  /* side A / side B flip */
  let currentSide = "A";

  function initSideFlip() {
    const flipBtn = document.getElementById("flip-side");
    const sideLabel = document.getElementById("side-label");
    const playerArt = document.getElementById("player-vinyl-art");
    if (!flipBtn || !sideLabel || !playerArt) return;

    flipBtn.addEventListener("click", () => {
      currentSide = currentSide === "A" ? "B" : "A";
      sideLabel.innerHTML = currentSide === "A" ? "Side&nbsp;A" : "Side&nbsp;B";
      playerArt.src = currentSide === "A" ? CONFIG.vinylArt : CONFIG.vinylArtSideB;

      flipBtn.classList.add("is-flipping");
      window.setTimeout(() => flipBtn.classList.remove("is-flipping"), 500);
    });
  }

  /* playlist ui */
  const playlistEl = document.getElementById("playlist");
  let currentIndex = 0;

  function buildPlaylist() {
    playlistEl.innerHTML = "";
    playlist.forEach((song, i) => {
      const li = document.createElement("li");
      li.className = "playlist__item";
      li.dataset.index = String(i);

      const btn = document.createElement("button");
      btn.className = "playlist__button";
      btn.type = "button";
      btn.textContent = song.title || `Track ${i + 1}`;
      btn.addEventListener("click", () => playSongAt(i));

      li.appendChild(btn);
      playlistEl.appendChild(li);
    });
  }

  function highlightActiveSong() {
    document.querySelectorAll(".playlist__item").forEach((li) => {
      li.classList.toggle("is-active", Number(li.dataset.index) === currentIndex);
    });
    const nowPlaying = document.getElementById("now-playing");
    const song = playlist[currentIndex];
    if (nowPlaying && song) {
      nowPlaying.textContent = song.title || `Track ${currentIndex + 1}`;
    }
  }

  /* youtube iframe api integration*/
  let ytPlayer = null;
  let ytReady = false;

  // Called automatically by the YouTube IFrame API script once loaded
  window.onYouTubeIframeAPIReady = function () {
    ytPlayer = new YT.Player("youtube-player", {
      height: "1",
      width: "1",
      videoId: "",
      playerVars: {
        controls: 0,
        disablekb: 1,
        modestbranding: 1,
        rel: 0,
        playsinline: 1,
      },
      events: {
        onReady: () => {
          ytReady = true;
          ytPlayer.setVolume(80);
        },
        onStateChange: onPlayerStateChange,
      },
    });
  };

  function onPlayerStateChange(event) {
    if (event.data === YT.PlayerState.PLAYING) {
      setPlayingUI(true);
    } else if (event.data === YT.PlayerState.PAUSED) {
      setPlayingUI(false);
    } else if (event.data === YT.PlayerState.ENDED) {
      // keep playing straight through the list; stop after track 13.
      if (currentIndex < playlist.length - 1) {
        goNext();
      } else {
        setPlayingUI(false);
      }
    }
  }

  function loadAndPlay(index) {
    const song = playlist[index];
    if (!song || !song.youtubeId || !ytReady) {
      highlightActiveSong();
      return;
    }
    ytPlayer.loadVideoById(song.youtubeId);
  }

  function playSongAt(index) {
    if (index < 0 || index >= playlist.length) return;
    currentIndex = index;
    highlightActiveSong();
    loadAndPlay(index);
  }

  function goNext() {
    if (currentIndex < playlist.length - 1) playSongAt(currentIndex + 1);
  }

  function goPrev() {
    if (currentIndex > 0) playSongAt(currentIndex - 1);
  }

  function togglePlayPause() {
    if (!ytReady) return;
    const state = ytPlayer.getPlayerState();
    if (state === YT.PlayerState.PLAYING) {
      ytPlayer.pauseVideo();
    } else if (playlist[currentIndex] && playlist[currentIndex].youtubeId) {
      if (state === YT.PlayerState.CUED || state === -1 || state === YT.PlayerState.ENDED) {
        loadAndPlay(currentIndex);
      } else {
        ytPlayer.playVideo();
      }
    }
  }

  function pausePlayback() {
    if (ytReady && ytPlayer && typeof ytPlayer.pauseVideo === "function") {
      try { ytPlayer.pauseVideo(); } catch (e) { /* noop */ }
    }
  }

  /* synthesized needle-drop sound, no audio file needed */
  let audioCtx = null;

  function getAudioCtx() {
    if (!audioCtx) {
      const AC = window.AudioContext || window.webkitAudioContext;
      if (!AC) return null;
      audioCtx = new AC();
    }
    if (audioCtx.state === "suspended") audioCtx.resume();
    return audioCtx;
  }

  function playNeedleDropSound() {
    const ctx = getAudioCtx();
    if (!ctx) return;

    const now = ctx.currentTime;

    // a short burst of filtered noise for the "crackle"
    const bufferSize = ctx.sampleRate * 0.35;
    const buffer = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
    const data = buffer.getChannelData(0);
    for (let i = 0; i < bufferSize; i++) {
      data[i] = (Math.random() * 2 - 1) * Math.pow(1 - i / bufferSize, 2.2);
    }
    const noise = ctx.createBufferSource();
    noise.buffer = buffer;

    const noiseFilter = ctx.createBiquadFilter();
    noiseFilter.type = "bandpass";
    noiseFilter.frequency.value = 2400;
    noiseFilter.Q.value = 0.6;

    const noiseGain = ctx.createGain();
    noiseGain.gain.setValueAtTime(0.16, now);
    noiseGain.gain.exponentialRampToValueAtTime(0.001, now + 0.32);

    noise.connect(noiseFilter).connect(noiseGain).connect(ctx.destination);

    // a soft low "thud" for the stylus touching down
    const thud = ctx.createOscillator();
    thud.type = "sine";
    thud.frequency.setValueAtTime(120, now);
    thud.frequency.exponentialRampToValueAtTime(45, now + 0.12);

    const thudGain = ctx.createGain();
    thudGain.gain.setValueAtTime(0.22, now);
    thudGain.gain.exponentialRampToValueAtTime(0.001, now + 0.15);

    thud.connect(thudGain).connect(ctx.destination);

    noise.start(now);
    noise.stop(now + 0.35);
    thud.start(now);
    thud.stop(now + 0.16);
  }

  /* visual state, tonearm movement */
  const vinylRecord = document.getElementById("vinyl-record");
  const tonearm = document.getElementById("tonearm");
  const iconPlay = document.getElementById("icon-play");
  const iconPause = document.getElementById("icon-pause");
  const btnPlay = document.getElementById("btn-play");
  let wasPlaying = false;

  function setPlayingUI(isPlaying) {
    vinylRecord.classList.toggle("is-spinning", isPlaying);
    tonearm.classList.toggle("is-playing", isPlaying);
    iconPlay.style.display = isPlaying ? "none" : "block";
    iconPause.style.display = isPlaying ? "block" : "none";
    btnPlay.setAttribute("aria-label", isPlaying ? "Pause" : "Play");

    // the needle should "land" right as the tonearm finishes its swing onto the record
    if (isPlaying && !wasPlaying) {
      window.setTimeout(playNeedleDropSound, 950);
    }
    wasPlaying = isPlaying;
  }

  /* play, pause, next, previous */
  function initControls() {
    btnPlay.addEventListener("click", togglePlayPause);
    document.getElementById("btn-next").addEventListener("click", goNext);
    document.getElementById("btn-prev").addEventListener("click", goPrev);
  }

  /* grid of all photos */
  const galleryGrid = document.getElementById("gallery-grid");

  function buildGallery() {
    galleryGrid.innerHTML = "";
    photos.forEach((photo, i) => {
      const item = document.createElement("div");
      item.className = "gallery-item";
      // tilt per photo
      const tilt = ((i % 5) - 2) * 1.1;
      item.style.setProperty("--tilt", `${tilt}deg`);
      item.setAttribute("role", "button");
      item.setAttribute("tabindex", "0");
      item.setAttribute("aria-label", `Enlarge photograph ${i + 1}`);

      const img = document.createElement("img");
      img.src = photo.src;
      img.loading = "lazy";
      img.decoding = "async";
      img.alt = photo.caption || `Photograph ${i + 1}`;
      img.onerror = function () {
        // keep the grid looking tidy even before real photos are added
        item.style.minHeight = "160px";
        item.style.background =
          "linear-gradient(155deg, var(--beige), var(--cream-deep))";
      };

      item.appendChild(img);
      item.addEventListener("click", () => openEnlargedPhoto(photo, i));
      item.addEventListener("keydown", (e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          openEnlargedPhoto(photo, i);
        }
      });
      galleryGrid.appendChild(item);
    });
  }

  /* photo enlarge */
  const enlargeOverlay = document.getElementById("photo-enlarge");
  const enlargeImg = document.getElementById("photo-enlarge-img");
  const enlargeCaption = document.getElementById("photo-enlarge-caption");

  function openEnlargedPhoto(photo, index) {
    enlargeImg.src = photo.src;
    enlargeImg.alt = photo.caption || `Photograph ${index + 1}`;
    enlargeCaption.textContent = photo.caption || "";
    enlargeOverlay.hidden = false;
    document.body.style.overflow = "hidden";
  }

  function closeEnlargedPhoto() {
    enlargeOverlay.hidden = true;
    document.body.style.overflow = "";
  }

  function initEnlargeOverlay() {
    document.getElementById("photo-enlarge-close").addEventListener("click", closeEnlargedPhoto);
    enlargeImg.addEventListener("click", closeEnlargedPhoto);
    enlargeOverlay.addEventListener("click", (e) => {
      if (e.target === enlargeOverlay) closeEnlargedPhoto();
    });
    document.addEventListener("keydown", (e) => {
      if (!enlargeOverlay.hidden && e.key === "Escape") closeEnlargedPhoto();
    });
  }

  /* hidden letter easter egg */
  const letterOverlay = document.getElementById("letter-overlay");
  const letterText = document.getElementById("letter-overlay-text");

  function openLetter() {
    letterText.textContent = CONFIG.hiddenLetterText;
    letterOverlay.hidden = false;
    document.body.style.overflow = "hidden";
  }

  function closeLetter() {
    letterOverlay.hidden = true;
    document.body.style.overflow = "";
  }

  function initHiddenLetter() {
    const trigger = document.getElementById("hidden-letter");
    if (!trigger) return;
    trigger.addEventListener("click", openLetter);
    document.getElementById("letter-overlay-close").addEventListener("click", closeLetter);
    letterOverlay.addEventListener("click", (e) => {
      if (e.target === letterOverlay) closeLetter();
    });
    document.addEventListener("keydown", (e) => {
      if (!letterOverlay.hidden && e.key === "Escape") closeLetter();
    });
  }

  /* journal: password gate, entries, composer, and the copy-to-file snippet */
  const JOURNAL_SESSION_KEY = "keepsake-journal-unlocked";
  let previewEntries = []; // entries added this session, before being pasted into script.js

  function isJournalUnlocked() {
    try {
      return sessionStorage.getItem(JOURNAL_SESSION_KEY) === "1";
    } catch (e) {
      return false;
    }
  }

  function setJournalUnlocked() {
    try {
      sessionStorage.setItem(JOURNAL_SESSION_KEY, "1");
    } catch (e) { /* noop */ }
  }

  function refreshJournalLockState() {
    const lock = document.getElementById("journal-lock");
    const content = document.getElementById("journal-content");
    if (!lock || !content) return;
    const unlocked = isJournalUnlocked();
    lock.hidden = unlocked;
    content.hidden = !unlocked;
    if (unlocked) buildJournalEntries();
  }

  function initJournalLock() {
    const form = document.getElementById("journal-lock-form");
    const input = document.getElementById("journal-password-input");
    const error = document.getElementById("journal-lock-error");
    if (!form) return;

    form.addEventListener("submit", (e) => {
      e.preventDefault();
      if (input.value === CONFIG.journalPassword) {
        error.hidden = true;
        input.value = "";
        setJournalUnlocked();
        refreshJournalLockState();
      } else {
        error.hidden = false;
      }
    });
  }

  function formatEntryDate(rawDate) {
    return rawDate && rawDate.trim() ? rawDate.trim() : "Undated";
  }

  function buildJournalEntries() {
    const container = document.getElementById("journal-entries");
    if (!container) return;
    container.innerHTML = "";

    const combined = journalEntries.concat(previewEntries);

    if (combined.length === 0) {
      const empty = document.createElement("p");
      empty.className = "journal-empty";
      empty.textContent = "No entries yet \u2014 tap the + to write the first one.";
      container.appendChild(empty);
      return;
    }

    combined.forEach((entry, i) => {
      const isPreview = i >= journalEntries.length;

      const card = document.createElement("div");
      card.className = "journal-entry";

      const dateRow = document.createElement("div");
      dateRow.className = "journal-entry__date";

      const dateText = document.createElement("span");
      dateText.textContent = formatEntryDate(entry.date);
      dateRow.appendChild(dateText);

      if (isPreview) {
        const tag = document.createElement("span");
        tag.className = "journal-entry__preview-tag";
        tag.textContent = "preview";
        dateRow.appendChild(tag);
      } else {
        const hint = document.createElement("span");
        hint.className = "journal-entry__hint";
        hint.textContent = "tap to read";
        dateRow.appendChild(hint);
      }

      const textEl = document.createElement("p");
      textEl.className = "journal-entry__text";
      textEl.textContent = entry.text || "";

      card.appendChild(dateRow);
      card.appendChild(textEl);
      card.addEventListener("click", () => card.classList.toggle("is-open"));

      container.appendChild(card);
    });
  }

  function escapeForJsString(str) {
    return String(str).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
  }

  function initJournalComposer() {
    const addButton = document.getElementById("journal-add-button");
    const composer = document.getElementById("journal-composer");
    const dateInput = document.getElementById("journal-composer-date");
    const textInput = document.getElementById("journal-composer-text");
    const cancelBtn = document.getElementById("journal-composer-cancel");
    const saveBtn = document.getElementById("journal-composer-save");

    const snippetOverlay = document.getElementById("journal-snippet");
    const snippetTextarea = document.getElementById("journal-snippet-text");
    const snippetCopy = document.getElementById("journal-snippet-copy");
    const snippetDone = document.getElementById("journal-snippet-done");

    if (!addButton) return;

    function openComposer() {
      const today = new Date();
      dateInput.value = today.toLocaleDateString(undefined, {
        year: "numeric",
        month: "long",
        day: "numeric",
      });
      textInput.value = "";
      composer.hidden = false;
      window.setTimeout(() => textInput.focus(), 50);
    }

    function closeComposer() {
      composer.hidden = true;
    }

    addButton.addEventListener("click", openComposer);
    cancelBtn.addEventListener("click", closeComposer);
    composer.addEventListener("click", (e) => {
      if (e.target === composer) closeComposer();
    });

    saveBtn.addEventListener("click", () => {
      const date = dateInput.value.trim();
      const text = textInput.value.trim();
      if (!text) {
        textInput.focus();
        return;
      }

      previewEntries.push({ date, text });
      closeComposer();
      buildJournalEntries();

      const snippet =
        `  { date: "${escapeForJsString(date)}", text: "${escapeForJsString(text)}" },`;
      snippetTextarea.value = snippet;
      snippetOverlay.hidden = false;
    });

    snippetDone.addEventListener("click", () => {
      snippetOverlay.hidden = true;
    });
    snippetOverlay.addEventListener("click", (e) => {
      if (e.target === snippetOverlay) snippetOverlay.hidden = true;
    });

    snippetCopy.addEventListener("click", () => {
      snippetTextarea.select();
      try {
        navigator.clipboard.writeText(snippetTextarea.value);
      } catch (e) {
        document.execCommand("copy");
      }
      snippetCopy.textContent = "copied!";
      window.setTimeout(() => { snippetCopy.textContent = "copy snippet"; }, 1600);
    });
  }

  function init() {
    applyConfig();
    initNavigation();
    buildPlaylist();
    buildGallery();
    initControls();
    initEnlargeOverlay();
    initSideFlip();
    initHiddenLetter();
    initJournalLock();
    initJournalComposer();
    highlightActiveSong();
  }

  document.addEventListener("DOMContentLoaded", init);
})();
